//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginForm.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.SaveDataSoap")]
    public interface SaveDataSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveFormData", ReplyAction="*")]
        LoginForm.ServiceReference1.SaveFormDataResponse SaveFormData(LoginForm.ServiceReference1.SaveFormDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveFormData", ReplyAction="*")]
        System.Threading.Tasks.Task<LoginForm.ServiceReference1.SaveFormDataResponse> SaveFormDataAsync(LoginForm.ServiceReference1.SaveFormDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveFormDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveFormData", Namespace="http://tempuri.org/", Order=0)]
        public LoginForm.ServiceReference1.SaveFormDataRequestBody Body;
        
        public SaveFormDataRequest() {
        }
        
        public SaveFormDataRequest(LoginForm.ServiceReference1.SaveFormDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveFormDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string courses;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal total;
        
        public SaveFormDataRequestBody() {
        }
        
        public SaveFormDataRequestBody(string name, string address, string gender, string state, string phone, string courses, decimal total) {
            this.name = name;
            this.address = address;
            this.gender = gender;
            this.state = state;
            this.phone = phone;
            this.courses = courses;
            this.total = total;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveFormDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveFormDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public LoginForm.ServiceReference1.SaveFormDataResponseBody Body;
        
        public SaveFormDataResponse() {
        }
        
        public SaveFormDataResponse(LoginForm.ServiceReference1.SaveFormDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveFormDataResponseBody {
        
        public SaveFormDataResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SaveDataSoapChannel : LoginForm.ServiceReference1.SaveDataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveDataSoapClient : System.ServiceModel.ClientBase<LoginForm.ServiceReference1.SaveDataSoap>, LoginForm.ServiceReference1.SaveDataSoap {
        
        public SaveDataSoapClient() {
        }
        
        public SaveDataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SaveDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaveDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaveDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LoginForm.ServiceReference1.SaveFormDataResponse LoginForm.ServiceReference1.SaveDataSoap.SaveFormData(LoginForm.ServiceReference1.SaveFormDataRequest request) {
            return base.Channel.SaveFormData(request);
        }
        
        public void SaveFormData(string name, string address, string gender, string state, string phone, string courses, decimal total) {
            LoginForm.ServiceReference1.SaveFormDataRequest inValue = new LoginForm.ServiceReference1.SaveFormDataRequest();
            inValue.Body = new LoginForm.ServiceReference1.SaveFormDataRequestBody();
            inValue.Body.name = name;
            inValue.Body.address = address;
            inValue.Body.gender = gender;
            inValue.Body.state = state;
            inValue.Body.phone = phone;
            inValue.Body.courses = courses;
            inValue.Body.total = total;
            LoginForm.ServiceReference1.SaveFormDataResponse retVal = ((LoginForm.ServiceReference1.SaveDataSoap)(this)).SaveFormData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LoginForm.ServiceReference1.SaveFormDataResponse> LoginForm.ServiceReference1.SaveDataSoap.SaveFormDataAsync(LoginForm.ServiceReference1.SaveFormDataRequest request) {
            return base.Channel.SaveFormDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<LoginForm.ServiceReference1.SaveFormDataResponse> SaveFormDataAsync(string name, string address, string gender, string state, string phone, string courses, decimal total) {
            LoginForm.ServiceReference1.SaveFormDataRequest inValue = new LoginForm.ServiceReference1.SaveFormDataRequest();
            inValue.Body = new LoginForm.ServiceReference1.SaveFormDataRequestBody();
            inValue.Body.name = name;
            inValue.Body.address = address;
            inValue.Body.gender = gender;
            inValue.Body.state = state;
            inValue.Body.phone = phone;
            inValue.Body.courses = courses;
            inValue.Body.total = total;
            return ((LoginForm.ServiceReference1.SaveDataSoap)(this)).SaveFormDataAsync(inValue);
        }
    }
}
